# Generated by Django 2.1.5 on 2019-01-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
